### ISSUE TITLE
Let's share this plugin and remove the OMF brand maybe?

### ISSUE THREAD

**Issue by ghost** [tuvistavie/oh-my-fish-core#1]
It would for the best if Fisherman could use this plugin too instead of rolling my own copy of my own code (see the irony?).

How thoroughly have you tested this BTW? Do things just work with `autoload` and `require`.

There are a few other things that would need to be added in order for this to work well with Fisherman too.

P.S: Probably not even an issue, but just to be safe, is the copyright properly attributed? I see you added Oh My Fish!'s  LICENSE. On the other hand, this is not a fork of OMF either.

**Comment by danhper** [comment]
I tried a few omf plugins depending on the core, and it seemed to work fine, but I I don't use it personally and didn't test it very thoroughly.

I'm completely open to modifying it to make it work with Fisherman. What changes would be needed?

For the license, oh-my-fish is under MIT license, so as long as I keep that license here I don't think there should be any problem.
For the name, I think it is more explicit to keep the OMF brand here as it would make it more obvious for new users that it can be needed for plugins with the OMF brand.

**Comment by bucaran** [comment]
Great!

So, when I said brand I think I meant the logo.

Well, let me see what I cook up. I just thought of an alternative regarding the OMF compatibility issue.

**Comment by ghost** [comment]
@tuvistavie I just published [autoinit](https://travis-ci.org/bucaran/fish-autoinit) to support those pesky init events. Now, using this repo makes perfect sense. Would you consider renaming it to `omf-core`, oh-my-fish is too wide and does not look so good when listing plugins.

On a second thought, there is a little issue. It would be great if we could add a `fishfile` at the root of the project so that Fisherman can download `autoinit` as a dependency when users try to install this plugin.

**Comment by danhper** [comment]
@bucaran Nice work!! Yeah, `omf-core` seems much better, I'll rename this!
Adding a fishfie with

```
autoinit
```

in it should be enough right?

**Comment by ghost** [comment]
@tuvistavie Thanks, but nevermind that. I figured it would be better in the long run, you know, to break this up into smaller modules.
- `git-helpers`
- `available`
- `refresh`

## 
- `omf-core` (require and autoload) + a fishfile adding the plugins listed above.

Too bad, but since those plugins are not yet published or anything, I am recommending Fisherman users to use your repo until I can figure out the nicest solution.

**Comment by danhper** [comment]
@bucaran I agree it would be better to split that out.
Do you want me to do this, or will you be creating another repository?

**Comment by ghost** [comment]
Alright, if you are up for this, then let's divide the work.

There should be one `omf` (I don't see the point of calling it omf-core) plugin that has those very OMF specific functions like `autoload` and `require`.

I kind of despire `available` (even though I wrote all of this code), but it should be their own "plugin". The same goes for `prompt_segments` and `git-helpers` or `git-is` (because all the functions are git-is-*).

Don't worry about tests, I'll add tests for all the easy ones as well as `git` ones. The only ones who will remain without tests are the OMF ones as OMF itself has no tests.

**Comment by danhper** [comment]
LGTM. I would rather go with `git-helpers` than `git-is` though because
it is easier to know what the plugin is for, and there are the `git_branch`
and `git_ahead` functions which do not match this name.
Why not create an organization, `fisherman-plugins` or something like this,
for "semi-official" plugins where we could put all that stuff?

**Comment by ghost** [comment]
> I would rather go with git-helpers

OK.

> Why not create an organization, fisherman-plugins or something like this,
> for "semi-official" plugins where we could put all that stuff?

Mmm. Did the same thing already once with `wa` and Wahoo. And Oh My Fish! has done it too. With Fisherman this is not really necessary because there is the ["index"](https://github.com/fisherman/fisher-index/blob/master/INDEX), but you have a point. It would be weird to add any OMF related plugins into the Fisherman org however, so we could create a kind of neutral organization.

Alright, let's see, what about:
- fish-plugins
- fishline
- fishmarks
- fishnuggets
- fishery

?

**Comment by danhper** [comment]
Yeah, I do not think that adding this to the fisherman org would be a good idea.
Better keep that clean.
I know about the index, but it is simply to keep things a little more organized.
I like fishery pretty much!

**Comment by ghost** [comment]
Me too!, but what about the SEO value though? `fishshell-plugins` sounds lame, but it would probably get better rankings. We can change the name later if it's still available.

**Comment by danhper** [comment]
If you care about SEO I agree `fishshell-plugins` should be better, though it does not sound very neat.
But anyway I do not think anyone is going to link this organization directly,
but rather the fisherman homepage or repository, so I do not think it is worth trying to
optimize search results for this organization.
What do you think?

**Comment by ghost** [comment]
I already sent you an invitation to Fishery.

**Comment by danhper** [comment]
Thanks! I'll add git-helpers to start with.

**Comment by ghost** [comment]
@tuvistavie Thanks for the hard work man!

While it's true the code is coming from the OMF repo, don't forget it actually has its origin here:

https://github.com/bucaran/wahoo/tree/master/lib

So, it's rather odd to credit Oh My Fish! in this case.

**Comment by danhper** [comment]
No problem!
Yeah, I am not really sure what we are supposed to do for the license.
If you want to change or remove it, I am fine, but I just do not want
to create any trouble as I do not think it is worth it.

**Comment by ghost** [comment]
No worries, this is not even remotely my greatest code, but credit shall be done correctly. Another reason I wanted to split things up was in order to take care of the copyright issue more easily. To be fair, the only function from that list that I did not create myself is `require`, but that one is not too far from [`import`](https://github.com/oh-my-fish/oh-my-fish/blob/4d628d5f43dbe8b138605d1f6ecbd762187afd7f/functions/import.fish) and [`__prepend_tree`](https://github.com/oh-my-fish/oh-my-fish/blob/4d628d5f43dbe8b138605d1f6ecbd762187afd7f/functions/_prepend_tree.fish), which I authored in the original "legacy" OMF to which I contributed extensively. ま

**Comment by bucaran** [comment]
What about a logo? You know I love them.

Here is a draft, do you have any ideas?

![1](https://cloud.githubusercontent.com/assets/8317250/12816985/e2923678-cb92-11e5-8520-52593b9e7378.png)

**Comment by ghost** [comment]
:)
